version: 21
currency:
  prefix: "Rp"
  thousands-separator: "."
  starting-balance: 10000

mysql:
  enabled: true
  host: "mysql.discord.sgp2.shockbyte.host"
  port: 3306
  database: "678e110c69-coresystem"
  username: "678e110c69-coresystem-admin"
  password: "019fa0b2cbeb140b"
  table-prefix: "rke_"
  pool:
    max-pool-size: 10
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000

settings:
  min-playtime-hours-to-sell: 5
  transaction-cooldown-ms: 700
  auto-refund-old-player-shop-on-first-start: true
  keep-backup-before-migration: true
  demand-price-update-minutes: 30
  voucher-apply-to-player-market: false
  daily-reset-hour: 0
sell-rules:
  allowed-categories:
    - mobdrops
    - farming
  blocked-message-category-info: "&7To maintain server economy, only &aMob Drops &7and &aFarming &7items can be sold to the server."
old-player-shop:
  search-files:
    - "plugins/RumahKitaEconomy/json/player-market-rupiah.json"
    - "plugins/RumahKitaEconomy/json/player-market.json"
    - "plugins/RumahKitaEconomy/player-market.json"
    - "plugins/RumahKitaEconomyRupiah/json/player-market-rupiah.json"
    - "plugins/RumahKitaEconomyRupiah/player-market-rupiah.json"

points:
  playtime:
    enabled: true
    interval-minutes: 30
    amount: 10
  afk:
    enabled: true
    interval-minutes: 10
    amount: 5
    world: "world"
    x: 0.0
    y: 64.0
    z: 0.0
    radius: 10.0
  kill-player:
    enabled: true
    amount: 15
  pvp:
    enabled: true
    amount: 15
